---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fog-api
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: fog-api
        image: nginx:alpine
        env:
        - name: KEDA_SERVICEBUS_AUTH_MODE
          value: ConnectionString
        - name: KEDA_SERVICEBUS_TOPIC_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
             name: keda-servicebus
             key: servicebus-connectionstring
        - name: KEDA_SERVICEBUS_TOPIC_NAME
          value: fog_device
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80

---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: keda-servicebus
#data:  
#  servicebus-connectionstring: RW5kcG9pbnQ9c2I6Ly9ldmdlbml5LWRldi1zZXJ2aWNlYnVzLnNlcnZpY2VidXMud2luZG93cy5uZXQvO1NoYXJlZEFjY2Vzc0tleU5hbWU9a2VkYS1vcGVyYXRvcjtTaGFyZWRBY2Nlc3NLZXk9ODR1bVMzR3ZXS3cxZDNDTWRhNWVZVndhMTZJOCtVcFMrK0FTYkJhbUhXcz07RW50aXR5UGF0aD1mb2dfZGV2aWNlCg==


---

apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keyvault-auth
spec:
  azureKeyVault:
    vaultUri: https://evgeniy-kv.vault.azure.net/
    secrets:
    - parameter: Secrets
      name: fog-api-service-bus
      version: 552494bc0980478cb4b45530f950bc73
     
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: fog-api-azure-servicebus
spec:
  scaleTargetRef:
    kind: Deployment
    name: fog-api
  pollingInterval: 30
  cooldownPeriod: 60
  minReplicaCount: 1
  maxReplicaCount: 4

  triggers:
  - type: azure-servicebus
    metadata:
      connectionFromEnv: "true"
      topicName: fog_device
      subscriptionName: fog
      messageCount: "5"
      activationMessageCount: "2"
    authenticationRef:
      name: keyvault-auth

