---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        envFrom:
        - secretRef:
            name: keda-service-bus-connection #name of secret
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Secret
metadata:
  name: keda-service-bus-connection
data:  
  servicebus-connectionstring: #azure service bus connection string base64


---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: servicebus-auth
spec:
  secretTargetRef:
    - key: servicebus-connectionstring #key in secret
      name: keda-service-bus-connection #name of secret
      parameter: connection
      
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nginx-azure-servicebus
spec:
  scaleTargetRef:
    kind: Deployment
    name: nginx
  pollingInterval: 30
  cooldownPeriod: 60
  minReplicaCount: 1
  maxReplicaCount: 4

  triggers:
  - type: azure-servicebus
    metadata:
      topicName: nginx
      subscriptionName: nginx
      messageCount: "5"
      activationMessageCount: "2"
    authenticationRef:
      name: servicebus-auth #name of TriggerAuthentication
