---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fog-api
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: fog-api
        image: nginx:alpine
        envFrom:
        - secretRef:
            name: keda-servicebus-clientid
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Secret
metadata:
  name: keda-servicebus-clientid
data:  
  clientid: clientid #AAD clientId secret in base64 mode
 
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keyvault-auth
spec:
  azureKeyVault:
    vaultUri: https://cluster_name.vault.azure.net/
    credentials:
      clientId: clientId
      clientSecret:
        valueFrom:
          secretKeyRef:
            name: keda-servicebus-clientid
            key: clientid                                 
      tenantId: tenantId
    secrets:
    - parameter: connection
      name: fog-api-service-bus #secret name as configured in azure key vault
      version: version #version to use within secret name in azure key vault
     
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: fog-api-azure-servicebus
spec:
  scaleTargetRef:
    kind: Deployment
    name: fog-api
  pollingInterval: 30
  cooldownPeriod: 60
  minReplicaCount: 1
  maxReplicaCount: 4

  triggers:
  - type: azure-servicebus
    metadata:
      topicName: fog_device
      subscriptionName: fog
      messageCount: "5"
      activationMessageCount: "2"
    authenticationRef:
      name: keyvault-auth

  - type: azure-servicebus
    metadata:
      topicName: fog_device
      subscriptionName: home-service
      messageCount: "5"
      activationMessageCount: "2"
    authenticationRef:
      name: keyvault-auth
