---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fog-api
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: fog-api
        image: nginx:alpine
        envFrom:
        - secretRef:
            name: keda-servicebus
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Secret
metadata:
  name: keda-servicebus
data:  
  servicebus-connectionstring: connectionstring


---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-servicebus-auth
spec:
  secretTargetRef:
    - key: servicebus-connectionstring # key in secret
      name: keda-servicebus # name of secret
      parameter: connection
      
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: fog-api-azure-servicebus
spec:
  scaleTargetRef:
    kind: Deployment
    name: fog-api
  pollingInterval: 30
  cooldownPeriod: 60
  minReplicaCount: 1
  maxReplicaCount: 4

  triggers:
  - type: azure-servicebus
    metadata:
      topicName: fog_device
      subscriptionName: fog
      messageCount: "5"
      activationMessageCount: "2"
    authenticationRef:
      name: azure-servicebus-auth
